### ISSUE TITLE
Feature Request: Setting to Just Block Them All w/no dialogues!

### ISSUE THREAD

**Issue by marksz** [clod81/block_service_workers#19]
My Chromebooks were freezing up until I removed all my service workers.  Now I have enough ram to stop the virtual memory thrashing, but I'd sure like to not have to say no to every website I visit, as most want to install a service worker theses days.

"Service workers in my browser are like barnacles on my Internet surfboard."  Mark Zinzow

**Comment by mariusa** [comment]
Please add a setting for users to choose between 

* Block all new requests (existing ones continue to work. Link to chrome://serviceworker-internals/)

* Ask every time (current behavior)

This allows us to switch back to asking when actually wanting to enable a specific site, then back to Block all new.

**Comment by clod81** [comment]
from version `1.1.0` (currently in review in Chrome web store), the setting is going to be per domain, not individual SWs
