### ISSUE TITLE
One worker with different URLs

### ISSUE THREAD

**Issue by Antiever** [clod81/block_service_workers#21]
There are cases when on some domains service_worker.js is passed through the address of the article which leads to a kind of "bug"

![2022-03-29_23-41-13](https://user-images.githubusercontent.com/9666515/160704807-c1db580e-9716-4408-a590-08ce41744524.png)

It would be nice to be able to block the worker globally for the entire domain.

**Comment by chabala** [comment]
Yeah, we need some kind of editable filter list that we can use wildcards in, like ad blocker filters do: https://adblockplus.org/filter-cheatsheet

**Comment by clod81** [comment]
yeah good call. I'm pretty packed with things atm, I will see when I have a chance to implement this. or PR welcome :)

**Comment by clod81** [comment]
From version `1.1.0` the setting is for the whole domain, not per individual SW in the domain.
The release in Chrome web store is in review, when approved the new functionality should work as expected

**Comment by clod81** [comment]
FYI: the new version has been published on the Chrome Store
